sudo: false

language: generic

cache:
  directories:
    - $HOME/.stack

env:
  - STACK_YAML=stack-ghc-7.8.yaml
  - STACK_YAML=stack.yaml

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
  - stack build --ghc-options=-Werror --no-terminal
  - stack test --ghc-options=-Werror --no-terminal
